### PR TITLE
Updating babel-istanbul to v0.5.5 to support babel v6.x.x

### PR DESCRIPTION
**Pull request by kkglobes**
I wanted to update this library to support the latest Babel v6 release. I found that babel-istanbul had been updated so the update to this library was very possible.

I have all of the tests passing and added one small test. 

Please let me know how this looks or if there are any improvements that need to be made.

### CODE REVIEW

**Comment by noamokman** [comment]
:+1: also, [babel-istanbul](https://github.com/ambitioninc/babel-istanbul) is now 0.5.8

**Comment by noamokman** [comment]
@cb1kenobi Ping :smile:

**Comment by cb1kenobi** [comment]
@noamokman So sorry. I didn't get any notifications that a PR was created. I'll review and publish this as soon as possible. Hang in there and THANK YOU for the PR!

**Comment by kkglobes** [comment]
@noamokman @cb1kenobi Thanks! 

@cb1kenobi I'll update babel-istanbul to 0.5.8 and make sure the tests still pass.

**Comment by noamokman** [comment]
Great!

**Comment by noamokman** [comment]
@cb1kenobi Maybe you didn't get the notification, so.. Ping :bell:

**Comment by cb1kenobi** [comment]
Reviewed and tested. Looks great! Thank you for your patience. I really appreciate the contribution. I'll be publishing a 0.10.2 here momentarily.

**Comment by kkglobes** [comment]
Thanks @cb1kenobi! And thanks @noamokman for your persistence :smile:

**Comment by cb1kenobi** [comment]
I published a couple hours ago: https://www.npmjs.com/package/gulp-babel-istanbul.

Enjoy!

**Comment by kkglobes** [comment]
@cb1kenobi I wanted to request that the version be bumped to 0.11.0. This is a breaking change since it's using the new babel-istanbul and babel 6. Let me know what you think.

**Comment by cb1kenobi** [comment]
@kkglobes Good idea and done! v0.11.0 is live! https://www.npmjs.com/package/gulp-babel-istanbul

**Comment by kkglobes** [comment]
@cb1kenobi Thanks!

**Pull request merged**
